from pathlib import Path
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib.units import cm
from reportlab.lib.utils import ImageReader
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import time
import traceback


def generate_pdf_evaluation(city_name: str, result: dict, output_dir: Path):
    """
    Membuat file PDF berjudul 'Evaluasi - <Kota>' berisi hasil training/prediksi.
    Output: Path PDF yang dihasilkan (atau None jika gagal)

    city_name : nama kota (str)
    result    : dict hasil training, contoh:
                {
                  'best_r2': 0.92,
                  'test_days': 30,
                  'n_total': 180,
                  'metrics': {'r2':0.92, 'mae':150, 'best_params': {...}},
                  'predictions': {'1':{'date':'2025-10-18','value':14500}, ...},
                  'trend': {'dates':[...], 'values':[...]}
                }
    output_dir: folder untuk menyimpan file PDF
    """
    try:
        output_dir.mkdir(parents=True, exist_ok=True)
        city_safe = str(city_name).replace('/', '_').replace('\\', '_').strip()
        pdf_path = output_dir / f"{city_safe}__evaluasi.pdf"

        # optional: buat plot tren jika ada
        trend_png = None
        try:
            trend = result.get('trend')
            if trend and trend.get('dates') and trend.get('values'):
                png_path = output_dir / f"{city_safe}__trend.png"
                plt.figure(figsize=(6, 3))
                plt.plot(trend['dates'], trend['values'], marker='o', linewidth=1)
                plt.title(f"Trend Harga - {city_safe}")
                plt.xlabel("Tanggal")
                plt.ylabel("Harga (Rp)")
                plt.xticks(rotation=45)
                plt.tight_layout()
                plt.savefig(png_path)
                plt.close()
                trend_png = png_path
        except Exception as e:
            print(f"[WARN] gagal buat trend chart untuk {city_safe}: {e}")

        # mulai buat PDF
        c = canvas.Canvas(str(pdf_path), pagesize=A4)
        w, h = A4
        y = h - 2 * cm

        # ===== HEADER =====
        c.setFont("Helvetica-Bold", 18)
        c.drawString(2 * cm, y, f"EVALUASI — {city_safe}")
        y -= 1.2 * cm
        c.setFont("Helvetica", 10)
        c.drawString(2 * cm, y, f"Generated: {time.strftime('%Y-%m-%d %H:%M:%S')}")
        y -= 0.8 * cm

        # ===== INFORMASI DASAR =====
        n_total = result.get("n_total", "-")
        test_days = result.get("test_days", "-")
        best_r2 = result.get("best_r2", "-")
        c.setFont("Helvetica-Bold", 12)
        c.drawString(2 * cm, y, "Informasi Data")
        y -= 0.6 * cm
        c.setFont("Helvetica", 10)
        c.drawString(2.2 * cm, y, f"Total Data (n_total): {n_total}")
        y -= 0.4 * cm
        c.drawString(2.2 * cm, y, f"Test Days: {test_days}")
        y -= 0.4 * cm
        c.drawString(2.2 * cm, y, f"Best R²: {best_r2}")
        y -= 0.8 * cm

        # ===== METRIK =====
        metrics = result.get("metrics", {})
        if metrics:
            c.setFont("Helvetica-Bold", 12)
            c.drawString(2 * cm, y, "Metrik Evaluasi")
            y -= 0.6 * cm
            c.setFont("Helvetica", 10)
            for k, v in metrics.items():
                if isinstance(v, (dict, list)):  # lewati struktur kompleks
                    continue
                c.drawString(2.2 * cm, y, f"{k}: {v}")
                y -= 0.4 * cm
            y -= 0.5 * cm

        # ===== PREDIKSI =====
        preds = result.get("predictions", {})
        if preds:
            c.setFont("Helvetica-Bold", 12)
            c.drawString(2 * cm, y, "Prediksi")
            y -= 0.6 * cm
            c.setFont("Helvetica", 10)
            for horizon, v in preds.items():
                if isinstance(v, dict):
                    val = v.get("value", "-")
                    date = v.get("date", "-")
                else:
                    val = v
                    date = "-"
                c.drawString(2.2 * cm, y, f"Horizon {horizon}: {val} (tgl: {date})")
                y -= 0.4 * cm
            y -= 0.6 * cm

        # ===== TREND CHART =====
        if trend_png and trend_png.exists():
            img_w = w - 4 * cm
            img_h = img_w * 0.4
            if y - img_h < 3 * cm:  # kalau kurang ruang → halaman baru
                c.showPage()
                y = h - 3 * cm
            c.drawImage(ImageReader(str(trend_png)), 2 * cm, y - img_h, width=img_w, height=img_h)
            y -= img_h + 0.5 * cm

        # ===== FOOTER =====
        c.setFont("Helvetica-Oblique", 8)
        c.drawString(2 * cm, 1.5 * cm, f"Generated by system — {time.strftime('%Y-%m-%d %H:%M:%S')}")

        c.save()
        print(f"[PDF] generated: {pdf_path}")
        return pdf_path

    except Exception as e:
        print("[ERROR] generate_pdf_evaluation:", e, traceback.format_exc())
        return None
